version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - docker.env
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - '27017:27017'
    env_file:
      - docker.env
