export const COUNTRY_CODES = {
  AU: "Australija",
  AT: "Austrija",
  BE: "Belgija",
  HR: "Hrvatska",
  CY: "Cipar",
  CZ: "Češka Republika",
  DK: "Danska",
  EE: "Estonija",
  FI: "Finska",
  FR: "Francuska",
  DE: "Njemačka",
  GR: "Grčka",
  HU: "Mađarska",
  IE: "Irska",
  IT: "Italija",
  LV: "Latvija",
  LI: "Lihtenštajn",
  LU: "Luksemburg",
  MT: "Malta",
  NL: "Nizozemska",
  NZ: "Novi Zeland",
  NO: "Norveška",
  PL: "Poljska",
  PT: "Portugal",
  RO: "Rumunjska",
  SG: "Singapur",
  SK: "Slovačka",
  SI: "Slovenija",
  ES: "Španjolska",
  SE: "Švedska",
  CH: "Švicarska",
  GB: "Ujedinjeno Kraljevstvo",
  US: "Sjedinjene Američke Države",
};
